### PR TITLE
More tests & edit term

### PR DESCRIPTION
**Pull request by huseinr2493**
Included in this version
- More tests for Course
- Edit term function and endpoint
- An `extractKeys` utility to prevent malicious editing
- Miscellaneous coverage

### CODE REVIEW

**Review by ErikDrake27 — APPROVED** [review]
Approved.

**Comment by huseinr2493** [comment]
Trying to reconcile differences with staging

**Comment by huseinr2493** [comment]
We now have two test suites for POST /course, we could either merge them or delete one of them, or just keep both.

**Review by joshua-elmer — APPROVED** [review]
Looks fine, but please remember that we were aiming to not add any new code or edits past noon yesterday so that everything was stable before the Sprint Review.

**Review by Slad3 — APPROVED** [review]

**Pull request merged**
