### PR TITLE
Added schema for course, term, and section

### PR DESCRIPTION
**Pull request by hstuewer**

### CODE REVIEW

**Review by ErikDrake27 — DISMISSED** [review]

**Comment by huseinr2493** [comment]
This crashes when run, definitely not merge ready yet.

**Comment by huseinr2493** [comment]
**`end`** is a reserved keyword in PostgreSQL, so `start` and `end` got renamed to `starttime` and `endtime`.

**Comment by huseinr2493** [comment]
Looks like this will work but I'm confused about the weekday parts. Wouldn't that only allow the value to be one (1) of the 7 weekdays in the check list?

**Comment by ErikDrake27** [comment]
I will bring this up in the meeting today, but I agree with Rahmi, the only value would be one of the days of the week.

**Review by Slad3 — APPROVED** [review]

**Comment by huseinr2493** [comment]
Just pushed a revamped design.

**Review by joshua-elmer — APPROVED** [review]
Looks like as it was discussed!

**Pull request merged**
