### PR TITLE
Edit users endpoint

### LINKED ISSUE #60: Real UPDATE queries are failing with syntax error
From my testing, it does not seem possible to use a **table name** as a parameter in a prepared statement. The result I got was:
```
syntax error at or near "$4"
```

I have also noticed a slight discrepancy in style consistency. The new update values helper incorporates the initial keyword `UPDATE ...` and the table name directly into it, which is a job normally reserved for the models. Perhaps this could be moved?

Thoughts?

### PR DESCRIPTION
**Pull request by ErikDrake27**

### CODE REVIEW

**Comment by ErikDrake27** [comment]
This needs updating hit create PR accidentally.

**Review by Slad3 — APPROVED** [review]

**Comment by huseinr2493** [comment]
Tests can possibly be made more complete by expecting User model functions to have been called with certain parameters
* The first time, `User.findOne` should be called with the contents of the Stytch authentication data
  * Or expect `not.toBeCalled()` if an error should prevent it from getting that far
* The second time, `User.findOne` should be called with the ID of the user we want to edit
* Finally, `User.edit` should have been called with valid parameters

**Comment by joshua-elmer** [comment]
> * Finally, `User.edit` should have been called with valid parameters

I can't speak for the first two points, but from what I can see the final test in the PUT does run user.edit with valid parameters and only passes when the successfully edited user is returned.

**Review by joshua-elmer — APPROVED** [review]
Nice work!

**Pull request merged**
