### PR TITLE
Get programs course

### PR DESCRIPTION
**Pull request by huseinr2493**
Program courses, with no auto-generated nonsense this time

**Still needs tests written.**

### CODE REVIEW

**Comment by ErikDrake27** [comment]
2 things Rahmi, one that can be done immediately and the other one need to wait for. Make sure you have your MD file in this PR, and then make sure this gets things as expected in insomnia/Postman once post programs get merged in, and take a screenshot.

**Review by bvoigt00 — CHANGES_REQUESTED** [review]
You need some unit tests for the stuff you added in ProgramCourse.js and program.js.

**Comment by huseinr2493** [comment]
Thank you all, working on it

**Comment by huseinr2493** [comment]
A new branch has been created containing the same stuff

**Pull request closed without merging**
