### PR TITLE
Added get function to Term.js

### PR DESCRIPTION
**Pull request by hstuewer**

### CODE REVIEW

**Comment by hstuewer** [comment]
The issue in the backlog said to use one id as a parameter and return one row. I wasn't sure whether to follow that or use findone and findall to standardize with the course functions. So we want to use findone and findall?

**Comment by joshua-elmer** [comment]
Yeah, the front end has expressed that they wanted a multi-get for everything and the user story just hadn't been updated.

**Comment by huseinr2493** [comment]
Looking good, it was 404'ing before because brand new routes need to be in /routes/index

**Review by ErikDrake27 — APPROVED** [review]
Looks good guys.

**Comment by ErikDrake27** [comment]
@Slad3 Make sure to approve and merge this one before approving and merging mine.

**Review by Slad3 — APPROVED** [review]

**Pull request merged**
